// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineGames.Models;

namespace OnlineGames.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineGames.Models.Igrica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cijena")
                        .HasColumnType("float");

                    b.Property<DateTime>("DatumIzlaska")
                        .HasColumnType("datetime2");

                    b.Property<string>("Izdavac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlikaIgriceId")
                        .HasColumnType("int");

                    b.Property<string>("Specifikacije")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SlikaIgriceId");

                    b.ToTable("Igrica");
                });

            modelBuilder.Entity("OnlineGames.Models.Kategorija", b =>
                {
                    b.Property<int>("KategorijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategorijaId");

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("OnlineGames.Models.KategorijaIgrica", b =>
                {
                    b.Property<int>("KategorijaIgricaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IgricaId")
                        .HasColumnType("int");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.HasKey("KategorijaIgricaId");

                    b.HasIndex("IgricaId");

                    b.HasIndex("KategorijaId");

                    b.ToTable("KategorijaIgrica");
                });

            modelBuilder.Entity("OnlineGames.Models.KorisnickiNalog", b =>
                {
                    b.Property<string>("KorisnickiNalogId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("KorisnickiNalogId");

                    b.ToTable("KorisnickiNalog");
                });

            modelBuilder.Entity("OnlineGames.Models.NalogIgrice", b =>
                {
                    b.Property<int>("NalogIgriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IgricaId")
                        .HasColumnType("int");

                    b.Property<string>("KorisnickiNalogId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NalogId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NalogIgriceId");

                    b.HasIndex("IgricaId");

                    b.HasIndex("KorisnickiNalogId");

                    b.ToTable("NalogIgrice");
                });

            modelBuilder.Entity("OnlineGames.Models.Novosti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Novosti");
                });

            modelBuilder.Entity("OnlineGames.Models.SlikaIgrice", b =>
                {
                    b.Property<int>("SlikaIgriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SlikaIgriceId");

                    b.ToTable("SlikaIgirce");
                });

            modelBuilder.Entity("OnlineGames.Models.Igrica", b =>
                {
                    b.HasOne("OnlineGames.Models.SlikaIgrice", "SlikaIgrice")
                        .WithMany()
                        .HasForeignKey("SlikaIgriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineGames.Models.KategorijaIgrica", b =>
                {
                    b.HasOne("OnlineGames.Models.Igrica", "Igrica")
                        .WithMany("KategorijaIgrica")
                        .HasForeignKey("IgricaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineGames.Models.Kategorija", "Kategorija")
                        .WithMany("KategorijaIgrica")
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineGames.Models.NalogIgrice", b =>
                {
                    b.HasOne("OnlineGames.Models.Igrica", "Igrica")
                        .WithMany("NalogIgrice")
                        .HasForeignKey("IgricaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineGames.Models.KorisnickiNalog", "KorisnickiNalog")
                        .WithMany("NalogIgrice")
                        .HasForeignKey("KorisnickiNalogId");
                });
#pragma warning restore 612, 618
        }
    }
}
